### PR TITLE
Enable usage on Github Enterprise 2.20

### PR DESCRIPTION
**Pull request by brevansio**
When testing with my company's Github Enterprise, I found that the GraphQL queries were out of date. Since using this in an Enterprise environment is one of the goals, I updated some of the logic to support GE 2.20.

Most of the changes are behind the scenes, but I did add a "Use Legacy Queries" checkbox to the Login View.

I'm curious what you think about this, so for now, please review without merging.

### CODE REVIEW

**Comment by Ckitakishi** [comment]
I think support Github Enterprise 2.20 is necessary, but I have a question, I'm curious whether the API is backward compatible, if so, we can write the minimum API requirements in the README, otherwise supporting multiple API versions would be tough...

**Comment by Ckitakishi** [comment]
BTW, what do you think about moving the "Use Legacy Queries" checkbox to setting view someday? 😆

**Comment by brevansio** [comment]
> I'm curious whether the API is backward compatible

Not really. I only got it working because of how GraphQL works. I'm actually using the new API and just not querying the newer stuff. 

That being said 2.20 is old enough that they dropped support lol. I don't know how to test it on other versions but it should work. In fact the "legacy API" should work with the current GitHub API.

**Comment by Ckitakishi** [comment]
>  I'm actually using the new API and just not querying the newer stuff.

Got it! I think separating newer/legacy looks good to me, it's good to get as much information as possible lol
(I'm starting to think a "API version" setting might be better than "Use Legacy Queries" check? But seems it's not easy..)

**Comment by brevansio** [comment]
Well I guess if we just look at the schema we should be able to tell which is supported by the "new" API and which needs the "old" API. I'll look at it tomorrow

**Comment by brevansio** [comment]
I (lightly) checked all the enterprise release documents. For our current state, I think we can support the following with this PR.

"New" API:
- Github AE
- Enterprise Cloud
- 3.2~3.3

"Legacy" API:
- 3.0~3.1 (Missing `PullRequest.viewerLatestReview`)
- 2.19~2.22 (Missing `PullRequest.isReadByViewer` and `PullRequest.viewerLatestReview`)

Unsupported (no GraphQL):
2.18 and below

**Comment by Ckitakishi** [comment]
> I (lightly) checked all the enterprise release documents. For our current state, I think we can support the following with this PR.

Thanks for your investigation!

**Review by Ckitakishi — APPROVED** [review]
LGTM for now!
(The only thing I care about is users need to specify whether to use legacy API, but we can improve in the future)

**Comment by brevansio** [comment]
> (The only thing I care about is users need to specify whether to use legacy API, but we can improve in the future)

Well, we could just use the legacy API for everyone. There are only two differences: 

1. There is no `isReadByViewer` so we can't tell if the user read the PR or not. ~Currently we don't use this information anyway.~ Currently this is only used as a filter.
2. There is no `viewerLatestReview` so we need to filter out all the reviews and find the last review. It takes some extra processing power, but that's it.

**Comment by Ckitakishi** [comment]
> Well, we could just use the legacy API for everyone. There are only two differences:

Then you need to revert some code, I don't think it's necessary.
We can decide whether to do so when receiving feedback from users~

**Pull request merged**
